#197 Implement peak filter for leading and tailing values
eclipse-chemclipse/chemclipse pull request #218
Opened 2020-01-14 16:32 UTC by alexstark4

Signed-off-by: Alexander Stark <alexander.stark@lablicate.com>

2020-01-14 16:35 UTC, alexstark4 commented
@eselmeister @laeubi @kerner1000 
Could you please review the filter.

2020-01-16 18:04 UTC, kerner1000 requested changes

2020-01-16 18:04 UTC, kerner1000 commented on chemclipse/plugins/org.eclipse.chemclipse.xxd.model/src/org/eclipse/chemclipse/xxd/model/support/ProcessPeaksByAsymmetricalPeakShapeFilterUtils.java
> +public class ProcessPeaksByAsymmetricalPeakShapeFilterUtils {
Just move static methods to the filter, no need for a helper class.

2020-01-20 14:10 UTC, kerner1000 approved these changes
Looks good to me.

2020-01-21 08:41 UTC, merged